name: Build Extension
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 16
      - run: yarn install
      - run: yarn build
      - uses: actions/upload-artifact@v4
        with:
          name: figma-extension-dist
          path: dist/
          
